spring:
  application:
    name: TypeTest
  datasource:
    username: root
    password: jnhc2831!
    url: jdbc:mysql://localhost:3306/type_test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: grooop.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml